name: Wakatime

on:
  workflow_dispatch:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'

jobs:
  update-readme:
    name: 'Update stats'
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          SHOW_TITLE: true
          USERNAME: ramezanius
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          COMMIT_MESSAGE: "Update WakaTime metrics"
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
